language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

install:
  - git fetch --tags
  - pip install coveralls tox-travis

  # generate some reflog for tests
  - ./init-tests-after-clone.sh

script:
  - tox

after_success:
  - coveralls